spring.application.name=pedidos
# Para correr localmente sin docker:
# acme.soap.url=http://localhost:8000/v3/19217075-6d4e-4818-98bc-416d1feb7b84

# Para correr dentro de docker apuntando a mock local:
# acme.soap.url=http://host.docker.internal:8000/v3/19217075-6d4e-4818-98bc-416d1feb7b84

# Para produccion:
acme.soap.url=https://jaimediaz.dev/v3/19217075-6d4e-4818-98bc-416d1feb7b84
